linters:
  disable-all: true
  enable:
    - deadcode
    - dupl
    - errcheck
    - goconst
    - gofmt
    - goimports
    - gomnd
    - misspell
    - predeclared
    - thelper
    - varcheck
    - whitespace

run:
  issues-exit-code: 0
  