version: '3.1'
services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "DummySQL786"
      MYSQL_ROOT_USER: "root"
      MYSQL_PASSWORD: "DummySQL786"
      MYSQL_DATABASE: "db"
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pDummySQL786"]
      interval: 2s
      timeout: 3s
      retries: 20

  api:
    container_name: go_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5020:5020"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=DummySQL786
      - DB_NAME=db
    volumes:
      - /home/g191387/Resumes:/app/Resumes
