version: '3.1'
services:
  db:
    image: mysql
    container_name:  "db"
    restart: always
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "DummySQL786"
      MYSQL_PASSWORD: "DummySQL786"
      MYSQL_DATABASE: "db"
    ports:
      - "3307:3306"
  
  api:
    container_name:  "go_api"
    # we want to use the image which is build from our Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5020:5020"
    # we are depending on the mysql backend
    depends_on:
      - db
    # We mount the working dir into the container, handy for development
    # This is what makes the hot reloading work inside of a Docker container
    volumes:
      - /home/sarmad/Desktop/FYP_Resumes:/app/Resumes